#ifndef OBSTACLE_CONFIG_H
#define OBSTACLE_CONFIG_H

#define DOG_OBSTACLE_WHEELBASE_MM             400.0f
#define DOG_OBSTACLE_WHEEL_AXLE_HEIGHT_MM      58.0f
#define DOG_OBSTACLE_BRIDGE_BOARD_MM           400.0f
#define DOG_OBSTACLE_BRIDGE_FINAL_GAP_MM       150.0f

/* Raise this to 100 and 150 only after the preceding soft-gap test passes. */
#define DOG_OBSTACLE_BRIDGE_ACTIVE_GAP_MM       50.0f
#define DOG_OBSTACLE_BRIDGE_TEST_GAP_LIMIT_MM   50.0f

#define DOG_OBSTACLE_BRIDGE_BODY_LOWER_MM       40.0f
#define DOG_OBSTACLE_BRIDGE_SWING_CLEARANCE_MM  30.0f
#define DOG_OBSTACLE_BRIDGE_PREPARE_MS         1500U
#define DOG_OBSTACLE_BRIDGE_SHIFT_MS           1200U
#define DOG_OBSTACLE_BRIDGE_SWING_MS           1800U
#define DOG_OBSTACLE_BRIDGE_TIMEOUT_MARGIN_MS  2500U

#define DOG_OBSTACLE_STAIR_STEP_HEIGHT_MM       100.0f
#define DOG_OBSTACLE_STAIR_TREAD_MM             300.0f
#define DOG_OBSTACLE_STAIR_LEVEL_COUNT            3U
#define DOG_OBSTACLE_STAIR_RUN_MM                900.0f
#define DOG_OBSTACLE_STAIR_WIDTH_MM              400.0f
#define DOG_OBSTACLE_STAIR_TOP_PLATFORM_MM      1000.0f
#define DOG_OBSTACLE_STAIR_TOTAL_LENGTH_MM      2800.0f
#define DOG_OBSTACLE_STAIR_EDGE_MARGIN_MM        58.0f
#define DOG_OBSTACLE_STAIR_COMPACT_X_MM         108.0f
#define DOG_OBSTACLE_STAIR_FRONT_FORWARD_X_MM   192.0f
#define DOG_OBSTACLE_STAIR_REAR_SHIFT_X_MM     (-192.0f)
#define DOG_OBSTACLE_STAIR_CLEARANCE_MM          40.0f
#define DOG_OBSTACLE_STAIR_FLAT_CLEARANCE_MM     30.0f

#define DOG_OBSTACLE_STAIR_PREPARE_MS          1500U
#define DOG_OBSTACLE_STAIR_LIFT_MS             1000U
#define DOG_OBSTACLE_STAIR_FORWARD_MS          1500U
#define DOG_OBSTACLE_STAIR_LAND_MS             1800U
#define DOG_OBSTACLE_STAIR_BODY_SHIFT_MS       2000U
#define DOG_OBSTACLE_STAIR_BODY_RAISE_MS       1800U
#define DOG_OBSTACLE_STAIR_DWELL_MS             300U
#define DOG_OBSTACLE_STAIR_TIMEOUT_MARGIN_MS   2500U

#endif
