#ifndef OBSTACLE_CONFIG_H
#define OBSTACLE_CONFIG_H

#define DOG_OBSTACLE_WHEELBASE_MM             400.0f
#define DOG_OBSTACLE_WHEEL_AXLE_HEIGHT_MM      58.0f
#define DOG_OBSTACLE_BRIDGE_BOARD_MM           400.0f
#define DOG_OBSTACLE_BRIDGE_FINAL_GAP_MM       150.0f

/* Raise this to 100 and 150 only after the preceding soft-gap test passes. */
#define DOG_OBSTACLE_BRIDGE_ACTIVE_GAP_MM       50.0f
#define DOG_OBSTACLE_BRIDGE_TEST_GAP_LIMIT_MM   50.0f

#define DOG_OBSTACLE_BRIDGE_BODY_LOWER_MM       40.0f
#define DOG_OBSTACLE_BRIDGE_SWING_CLEARANCE_MM  30.0f
#define DOG_OBSTACLE_BRIDGE_PREPARE_MS         1500U
#define DOG_OBSTACLE_BRIDGE_SHIFT_MS           1200U
#define DOG_OBSTACLE_BRIDGE_SWING_MS           1800U
#define DOG_OBSTACLE_BRIDGE_TIMEOUT_MARGIN_MS  2500U

#endif
