#ifndef OBSTACLE_CONFIG_H
#define OBSTACLE_CONFIG_H

#define DOG_OBSTACLE_WHEELBASE_MM             400.0f
#define DOG_OBSTACLE_STAIR_LOW_LANDING_MM        50.0f
#define DOG_OBSTACLE_STAIR_MID_LANDING_MM       100.0f
#define DOG_OBSTACLE_STAIR_HIGH_LANDING_MM      150.0f
#define DOG_OBSTACLE_STAIR_LOW_BODY_RAISE_MM      0.0f
#define DOG_OBSTACLE_STAIR_MID_BODY_RAISE_MM      0.0f
#define DOG_OBSTACLE_STAIR_HIGH_BODY_RAISE_MM    30.0f
#define DOG_OBSTACLE_STAIR_TREAD_MM             300.0f
#define DOG_OBSTACLE_STAIR_LEVEL_COUNT            1U
#define DOG_OBSTACLE_STAIR_WIDTH_MM              400.0f
#define DOG_OBSTACLE_STAIR_EDGE_MARGIN_MM        58.0f
#define DOG_OBSTACLE_STAIR_COMPACT_X_MM         108.0f
#define DOG_OBSTACLE_STAIR_FRONT_FORWARD_X_MM   192.0f
#define DOG_OBSTACLE_STAIR_REAR_SHIFT_X_MM     (-192.0f)
#define DOG_OBSTACLE_STAIR_FLAT_CLEARANCE_MM     30.0f

#define DOG_OBSTACLE_STAIR_BODY_PRERAISE_MS    1500U
#define DOG_OBSTACLE_STAIR_PREPARE_MS          1500U
#define DOG_OBSTACLE_STAIR_LIFT_MS             1000U
#define DOG_OBSTACLE_STAIR_FORWARD_MS          1500U
#define DOG_OBSTACLE_STAIR_LAND_MS             1800U
#define DOG_OBSTACLE_STAIR_BODY_SHIFT_MS       2000U
#define DOG_OBSTACLE_STAIR_BODY_RAISE_MS       1800U
#define DOG_OBSTACLE_STAIR_DWELL_MS             300U
#define DOG_OBSTACLE_STAIR_TIMEOUT_MARGIN_MS   2500U

#endif
