// AUTO-GENERATED by tools/generate.py. DO NOT EDIT.
// Sources: dm02.ioc, User/libxr_config.yaml, User/xrobot.yaml
// Generators: libxr 5.2.4, xrobot 0.3.1
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

void app_main(void);

#ifdef __cplusplus
}
#endif
